---

- name: Installing dependencies
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - lvm2
      - yum-utils
      - epel-release
      - device-mapper-persistent-data


- name: Adding YUM repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: "{{ centos_docker_ce_private_repo }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ centos_docker_ce_private_repo_gpg }}"

