---

- name: Installing dependencies
  apt:
    pkg: apt-transport-https
    state: present

- name: Adding APT key
  apt_key:
    id: "36A1D7869245C8950F966E92D8576A8BA88D21E9"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"

- name: Adding APT repository
  apt_repository:
    repo: 'deb https://get.docker.com/ubuntu docker main'
    update_cache: yes

- name: Installing APT packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-setuptools
    - "{{ docker_package }}"

- name: Installing Ansible dependencies
  easy_install:
    name: pip

- name: Installing Ansible PIP dependencies
  pip:
    name: docker-py
    state: present
