---

- import_tasks: install_ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: install_suse.yml
  when: ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'

- import_tasks: install_centos.yml
  when: ansible_distribution == 'CentOS'

- name: 'Installing Ansible dependencies'
  easy_install:
    name: pip

- name: 'Installing Ansible PIP dependencies'
  pip:
    name: "{{ item.name | default(item) }}"
    state: present
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ docker_pip_dependencies }}"
