---

- name: 'Adding YUM repository'
  yum_repository:
    name: docker-ce-stable
    description: "Docker CE Stable - $basearch"
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
    enabled: yes
    gpgcheck: yes
    gpgkey: "https://download.docker.com/linux/centos/gpg"

- name: 'Installing YUM packages'
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-setuptools
    - docker-ce
