---

- name: Installing dependencies
  apt: >
    pkg=python-pip
    state=present
  tags:
    - development
    - docker
    - install

- name: Installing python dependencies
  pip: >
    name=docker-py
    state=present
  tags:
    - development
    - docker
    - install

- name: Adding repository key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  tags:
    - development
    - docker
    - install

- name: Adding repository
  apt_repository: >
    repo='deb http://get.docker.io/ubuntu docker main'
    update_cache=yes
  tags:
    - development
    - docker
    - install

- name: Installing Docker
  apt: >
    pkg={{ docker_package }}
    state=present
  tags:
    - development
    - docker
    - install
