---

- include: install_ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: install_suse.yml
  when: ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'

- name: 'Docker > installing Ansible dependencies'
  easy_install:
    name: pip

- name: 'Docker > installing Ansible PIP dependencies'
  pip:
    name: docker-py
    state: present
