---

- name: Adding repository key
  apt_key: url="https://get.docker.io/gpg" id="A88D21E9"
  tags:
    - development
    - docker
    - install

- name: Adding repository
  apt_repository: >
    repo: 'deb http://get.docker.io/ubuntu docker main'
    update_cache: yes
  tags:
    - development
    - docker
    - install

- name: Installing Docker
  apt: pkg=lxc-docker
  tags:
    - development
    - docker
    - install

