---

- name: Adding APT key
  apt_key:
    id: "A88D21E9"
    url: "https://get.docker.io/gpg"

- name: Adding APT repository
  apt_repository:
    repo: 'deb https://get.docker.io/ubuntu docker main'
    update_cache: yes

- name: Installing Docker
  apt:
    name: "{{ docker_package }}"
    state: present
